compilers=&scale-nvcc-nvidia:&scale-nvcc-amd
supportsExecute=false
supportsBinary=false

group.scale-nvcc-nvidia.compilers=scalenvidia171
group.scale-nvcc-nvidia.compilerType=scale-nvcc-nvidia
group.scale-nvcc-nvidia.baseName=SCALE NVCC (NVIDIA)
group.scale-nvcc-nvidia.isSemVer=true
group.scale-nvcc-nvidia.includeFlag=-I
group.scale-nvcc-nvidia.rpathFlag=-L
group.scale-nvcc-nvidia.baseOptions=--cuda-path=/product/ubuntu24-x86_64/apps/CUDA/12.8.0 #-cubin
group.scale-nvcc-nvidia.nvdisasm=/product/ubuntu24-x86_64/apps/CUDA/12.8.0/bin/nvdisasm

compiler.scalenvidia171.semver=1.7.1
compiler.scalenvidia171.exe=/volatile/catA/rb263871/compiler-explorer/scale/1.7.1/llvm/bin/nvcc
compiler.scalenvidia171.ldPath=/product/ubuntu24-x86_64/apps/GCCcore/15.2.0/lib64
compiler.scalenvidia171.options=--compiler-bindir /product/ubuntu24-x86_64/apps/GCCcore/15.2.0/bin
compiler.scalenvidia171.demangler=/usr/bin/c++filt
compiler.scalenvidia171.objdumper=/usr/bin/objdump
group.scalenvidia171.nvdisasm=/product/ubuntu24-x86_64/apps/CUDA/12.8.0/bin/nvdisasm


group.scale-nvcc-amd.compilers=scaleamd171
group.scale-nvcc-amd.compilerType=scale-nvcc-amd
group.scale-nvcc-amd.baseName=SCALE NVCC (AMD)
group.scale-nvcc-amd.isSemVer=true
group.scale-nvcc-amd.includeFlag=-I
group.scale-nvcc-amd.rpathFlag=-L
group.scale-nvcc-amd.baseOptions=#-emit-llvm

compiler.scaleamd171.semver=1.7.1
compiler.scaleamd171.exe=/volatile/catA/rb263871/compiler-explorer/scale/1.7.1/targets/gfx1100/bin/nvcc
compiler.scaleamd171.ldPath=/product/ubuntu24-x86_64/apps/GCCcore/15.2.0/lib64
compiler.scaleamd171.options=--compiler-bindir /product/ubuntu24-x86_64/apps/GCCcore/15.2.0/bin
compiler.scaleamd171.demangler=/usr/bin/c++filt
compiler.scaleamd171.objdumper=/usr/bin/objdump